# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Workshop/HDL/53MHZtestok/53MHZtestok.srcs/sources_1/ip/dmem/dmem.xci
# IP: The module: 'dmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Workshop/HDL/53MHZtestok/53MHZtestok.gen/sources_1/ip/dmem/dmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Workshop/HDL/53MHZtestok/53MHZtestok.srcs/sources_1/ip/dmem/dmem.xci
# IP: The module: 'dmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Workshop/HDL/53MHZtestok/53MHZtestok.gen/sources_1/ip/dmem/dmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
